### ISSUE TITLE
Encodings 2.0

### ISSUE THREAD

**Issue by ljedrz** [ljedrz/lambda_calculus#25]
As Stump and Fu state in section [3 Previous Lambda Encodings](http://homepage.cs.uiowa.edu/~astump/papers/stump-fu-jfp-2016.pdf):
>  We elide the definitions of basic non-recursive datatypes for pair types, sum types, booleans, the unit type, and a maybe type. Because these are not recursive, the different lambda-encodings all agree for them.

This means there is room for a refactoring of the encoding modules; right now 4 options come to mind:
1. instruct the users to import `church::*` whenever they want to use non-numeric types (meh, that's just lazy)
2. import church functionalities into non-church modules (so much duplication)
3. create a module with common data encodings (getting warmer, but there is still a better way)
4. restructure the encoding modules so that the "types" are at the top level (aww yiss)

The hierarchy could look as follows:
```
src
|- combinators.rs
|- lib.rs
|- parser.rs
|- reduction.rs
|- term.rs
|- data (or encoding?)
   |- boolean.rs
   |- list (a good moment to include additional list encodings)
      |- one_pair.rs
      |- two_pair.rs
      |- rfold.rs
   |- mod.rs
   |- numerals
      |- church.rs
      |- mod.rs
      |- parigot.rs
      |- scott.rs
      |- stumpfu.rs
   |- option.rs
   |- pair.rs
```

Advantages:
- the `encoding` feature is easier to manage
- tests and benches can be done on a per-type basis (it's possible now, but the structure wouldn't be obvious); this would reduce the file count
- different numeral encodings can share common types

Disadvanages:
- quite a bit of work
- the conversions need to be re-thought
- slightly greater complexity

I'm open to suggestions; @billpmurphy?

**Comment by billpmurphy** [comment]
I like this design! I think it's possible to keep the conversions pretty ergonomic across encodings; it gets more tricky when different list types are involved. Consider the following cases:

* `1.to_church()` 
* `1.to_scott()`
* `Some(1).to_church()`
* `Some(1).to_scott()      //same as above except for the numeral`
* `vec![1, 2, 3].to_church()`
* `vec![1, 2, 3].to_scott()    //same as above except for the numeral`
* `Some(false).to_church()`
* `Some(false).to_scott()      //same as above`

All of this seems possible with the design you outlined (there will be a little duplication of `impl Trait`s for each of the encoding traits to make this work, but that doesn't seem too bad). However, I'm not sure how to make this design work when there are _also_ different types of e.g. lists that are shared across encodings.

**Comment by ljedrz** [comment]
That was actually much easier than I expected. I currently finished refactoring with a single list; it looks pretty good, so I'll merge it.

**Comment by ljedrz** [comment]
After some consideration I decided against adding different representations of lists; it could easily become a mess and the current one is the one most widely used and imo practical.
