### ISSUE TITLE
Not all list 2.0 function doctests are compatible with all numeral encodings

### ISSUE THREAD

**Issue by ljedrz** [ljedrz/lambda_calculus#28]
The following list functions cause issues in the doctests when used with Scott/Parigot/Stump-Fu numerals:
- `filter`
- `foldl`
- `foldr`
- `index`
- `length`
- `list`
- `map`
- `take`
- `take_while` (builds with Parigot/Stump-Fu)
- `zip_with`

This doesn't necessarily mean that the functions are not general enough - it might be the doctests' fault. The list integration test module needs to be extended with other encodings.

**Comment by ljedrz** [comment]
It appears that the Scott list is encoded a bit differently, as its `nil` is not `fls` but `tru` 😞. This might require a division of list types after all; I started the `scott_list` branch to work on this. There isn't too much information on non-Church lists encodings, but I'll keep searching.

Many list functions do work on different encodings, though, and I'm wondering how to approach this. Should they be split out as a separate `common` module or should I employ some macro magic? I'll give it some more thought.

**Comment by ljedrz** [comment]
Upon closer inspection some of these were just doctest-specific; the ones actually affected by different encodings seem to be:
- `length` (the result)
- `index` (the index)
- `list` (the number of items)
- `take` (the number to take)

I decided to introduce an `Encoding` enum to pass to affected functions. Some of them are easy to adjust, some more difficult. @billpmurphy would you like to help in adjusting `length`, `index` or `list`? I'll first try to create `is_zero` (needed for `take`) for the new encodings and to finish the integration test macros to test the new setup.

**Comment by billpmurphy** [comment]
Will do!

**Comment by billpmurphy** [comment]
Instead of changing some of the `list` functions to take an encoding parameter, I wonder if it's better to make `Encoding` into a trait + a collection of phantom types, and then parameterize functions that depend on encoding?

The end result is the API looks like `list::length::<Church>()` instead of `list::length(Church)` and variants that are not available won't compile.

**Comment by ljedrz** [comment]
I like this idea; I'm only wondering if it wouldn't make the API less straightforward for the beginners. I'll check how this would look in the docs.

**Comment by ljedrz** [comment]
I made an attempt, but it became messy and verbose. I have to admit, though, that I don't have much experience with this approach. If you are able to implement it cleanly, I'd definitely consider a relevant pull request.

Otherwise I don't think it's a big deal, as the current way doesn't have serious drawbacks (the performance/memory penalty is negligible) and maintains the "untypedness" feel of lambda calculus.

**Comment by ljedrz** [comment]
The last two functions to adjust to new encodings are:
- index
- list

I think that with these 2 ready I'll be ok with releasing version 2.0.

**Comment by ljedrz** [comment]
Actually, after having implemented other list variants in the [other-lists](https://github.com/ljedrz/lambda_calculus/tree/other_lists) branch (and taking into consideration the required haxx) I came to the conclusion that the Church-numeral-dependent single-pair list functions can just remain like that.

I'm still battling the idea of having different list implementations available in 2.0; they are interesting, but they increase the verbosity of all utility operations. This, however, might be a sign of relaying too much on them; I'm open to suggestions.
