### ISSUE TITLE
Unable to replicate the paper Fontana and Buss 1994 (https://link.springer.com/content/pdf/10.1007/BF02458289.pdf)

### ISSUE THREAD

**Issue by julianzxue** [ljedrz/lambda_calculus#47]
I'm a newcomer to lambda calculus.

https://link.springer.com/content/pdf/10.1007/BF02458289.pdf, Figure 1a

![image](https://user-images.githubusercontent.com/4522817/217419395-ec657dd0-2fea-4043-953a-47ccc9aceeaa.png)

The authors study the two expressions:

\a.(a)\b.\c.(c)\d.\e.(e)d 
\a.(a)\b.\c.(c)b

Such that the application of one on the other replicates the expressions. I can't seem to do that with this program. Parsing the first expression:

Original string: \a.(a)\b.\c.(c)\d.\e.(e)d
Parsed expression (not reduced): \a.\b.\c.\d.\e.e e e d
Reduced expression is same as above: \a.\b.\c.\d.\e.e e e d

Parsing the second expression similarly gets me

Original string: \a.(a)\b.\c.(c)b
Parsed expression (not reduced): \a.\b.\c.c c b
Reduced expression is same as above: \a.\b.\c.c c b

I'm not able to replicate the results of the original paper.

What am I doing wrong?

**Comment by ljedrz** [comment]
Thanks for the report! I can't check it out right now, but I'll do so soon 👍.

**Comment by julianzxue** [comment]
Thank you!!

**Comment by ljedrz** [comment]
Disclaimer: I haven't played with lambda calculus for a good while now, so please take this with a grain of salt :smiley:.

I think it's just the fact that you need to add some extra explicit parentheses, otherwise the parser will automatically fold/collapse some of the sub-expressions (as suggested by the results of your parsing); the following seems to do the trick:
```
let expr_a = parse(r#"\a. (a (\b. (\c. (c (\d. (\e. (e d)))))))"#, Classic).unwrap();
let expr_b = parse(r#"\a. (a (\b. (\c. (c b))))"#, Classic).unwrap();

assert_eq!(beta(app(expr_a.clone(), expr_b.clone()), NOR, 0), expr_b);
assert_eq!(beta(app(expr_b.clone(), expr_a.clone()), NOR, 0), expr_a);
```

**Comment by julianzxue** [comment]
That did the trick. It's so obvious but escaped me as the solution. Thanks
again!

**Comment by ljedrz** [comment]
Glad to hear it; I'll close the issue then 👍.
